// Autogenerated using mud system-types
import MoveSystem from "../abi/MoveSystem.json";
import ShootSystem from "../abi/ShootSystem.json";
import SpawnSystem from "../abi/SpawnSystem.json";
import TerrainSystem from "../abi/TerrainSystem.json";

export const SystemAbis = {
  "orion.system.move": MoveSystem.abi,
  "orion.system.shoot": ShootSystem.abi,
  "orion.system.spawn": SpawnSystem.abi,
  "orion.system.terrain": TerrainSystem.abi,
};
