// Autogenerated using mud system-types
export const systemToId = {
  MoveSystem: "orion.system.move",
  ShootSystem: "orion.system.shoot",
  SpawnSystem: "orion.system.spawn",
  TerrainSystem: "orion.system.terrain",
};

export const idToSystem = {
  "orion.system.move": "MoveSystem",
  "orion.system.shoot": "ShootSystem",
  "orion.system.spawn": "SpawnSystem",
  "orion.system.terrain": "TerrainSystem",
};
  