// Autogenerated using mud system-types
import { MoveSystem } from "./ethers-contracts/MoveSystem";
import { ShootSystem } from "./ethers-contracts/ShootSystem";
import { SpawnSystem } from "./ethers-contracts/SpawnSystem";
import { TerrainSystem } from "./ethers-contracts/TerrainSystem";
 
export type SystemTypes = {
  "orion.system.move": MoveSystem;
  "orion.system.shoot": ShootSystem;
  "orion.system.spawn": SpawnSystem;
  "orion.system.terrain": TerrainSystem;
};
